// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Social_Media_Web_API.Data;

#nullable disable

namespace Social_Media_Web_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Social_Media_Web_API.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "يا جماعة حد فاهم async await ده بيستنى ولا بيزوّغ؟ 😂",
                            CreatedAt = new DateTime(2025, 11, 1, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Just pushed to GitHub... and broke everything 💀",
                            CreatedAt = new DateTime(2025, 11, 1, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "النت وقع وقت الـ migration، حسّيت إني فقدت روحي 😭",
                            CreatedAt = new DateTime(2025, 11, 2, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Coffee ☕ + Code = Happiness 💻❤️",
                            CreatedAt = new DateTime(2025, 11, 2, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "النهارده قررت أكتب clean code... بعد أول bug رجعت عادي 😅",
                            CreatedAt = new DateTime(2025, 11, 3, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Content = "When you fix one bug and create three new ones 🤡",
                            CreatedAt = new DateTime(2025, 11, 3, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            Content = "مش عارف ليه كل ما أقول خلاص المشروع خلص، Visual Studio يضحك 😭",
                            CreatedAt = new DateTime(2025, 11, 4, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Content = "Flutter build time be like: go make a sandwich 😂",
                            CreatedAt = new DateTime(2025, 11, 4, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            Content = "الـ API شغالة تمام، بس الكلاينت بيقول مش شغالة 🤨",
                            CreatedAt = new DateTime(2025, 11, 5, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            Content = "life update: still debugging 🐛",
                            CreatedAt = new DateTime(2025, 11, 6, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Social_Media_Web_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "idont care",
                            Email = "sewedy@example.com",
                            Icon = "psychology",
                            UserName = "Sewedy"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Flutter Eng wants an offer 😑",
                            Email = "aya@example.com",
                            Icon = "emoji_events",
                            UserName = "Aya"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Pretty, huh? 🎨",
                            Email = "asia@example.com",
                            Icon = "brush",
                            UserName = "Asia"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Backend dev, send help ☕",
                            Email = "ashraqat@example.com",
                            Icon = "explore",
                            UserName = "Ashraqat"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "AI guy, robots > humans 🤖",
                            Email = "mostafa@example.com",
                            Icon = "smart_toy",
                            UserName = "Mostafa"
                        });
                });

            modelBuilder.Entity("Social_Media_Web_API.Models.Post", b =>
                {
                    b.HasOne("Social_Media_Web_API.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Social_Media_Web_API.Models.User", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
